language: node_js
node_js:
  - "node"
  - "lts/*"
deploy:
  - provider: npm
    skip_cleanup: true
    email: $NPM_EMAIL_ADDRESS
    api_key: $NPM_API_KEY
    tag: latest
    on:
      tags: true
      condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+$
